// Generated by github.com/romshark/icumsg/internal/cmd/gencldr. DO NOT EDIT.
// CLDR Version: 47
// Unicode Version: 16.0.0

package cldr

import "golang.org/x/text/language"

// Rules defines supported CLDR plural rules.
type Rules struct{ Zero, One, Two, Few, Many, Other bool }

// PluralRules defines supported cardinal and ordinal CLDR plural rules.
type PluralRules struct {
	Cardinal Rules
	Ordinal  Rules
}

// PluralRulesByTag maps language tags to supported plural rules.
var PluralRulesByTag = make(map[language.Tag]PluralRules, 219)

// PluralRulesByBase maps base languages to supported plural rules.
var PluralRulesByBase = make(map[language.Base]PluralRules, 219)

func init() {
	{
		PluralRulesByTag[language.Und] = PluralRules{
			Cardinal: Rules{Other: true}, Ordinal: Rules{Other: true},
		}
		undBase, _ := language.Und.Base()
		PluralRulesByBase[undBase] = PluralRules{
			Cardinal: Rules{Other: true}, Ordinal: Rules{Other: true},
		}
	}
	register := func(s string, cardinal, ordinal Rules, isBase bool) {
		l, err := language.Parse(s)
		if err != nil {
			panic(err)
		}
		PluralRulesByTag[l] = PluralRules{cardinal, ordinal}
		if isBase {
			base, _ := l.Base()
			PluralRulesByBase[base] = PluralRules{cardinal, ordinal}
		}
	}
	register("af",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ak",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("am",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("an",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ar",
		Rules{Other: true, Zero: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("ars",
		Rules{Other: true, Zero: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("as",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true, Many: true}, true)
	register("asa",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ast",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("az",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Few: true, Many: true}, true)
	register("bal",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("be",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true, Few: true}, true)
	register("bem",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("bez",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("bg",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("bho",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("blo",
		Rules{Other: true, Zero: true, One: true},
		Rules{Other: true, Zero: true, One: true, Few: true}, true)
	register("bm",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("bn",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true, Many: true}, true)
	register("bo",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("br",
		Rules{Other: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("brx",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("bs",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true}, true)
	register("ca",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, One: true, Two: true, Few: true}, true)
	register("ce",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ceb",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("cgg",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("chr",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ckb",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("cs",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("csw",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("cy",
		Rules{Other: true, Zero: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true, Zero: true, One: true, Two: true, Few: true, Many: true}, true)
	register("da",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("de",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("doi",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("dsb",
		Rules{Other: true, One: true, Two: true, Few: true},
		Rules{Other: true}, true)
	register("dv",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("dz",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("ee",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("el",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("en",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true}, true)
	register("eo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("es",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true}, true)
	register("et",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("eu",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("fa",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ff",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("fi",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("fil",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("fo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("fr",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, One: true}, true)
	register("fur",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("fy",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ga",
		Rules{Other: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true, One: true}, true)
	register("gd",
		Rules{Other: true, One: true, Two: true, Few: true},
		Rules{Other: true, One: true, Two: true, Few: true}, true)
	register("gl",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("gsw",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("gu",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true, Many: true}, true)
	register("guw",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("gv",
		Rules{Other: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("ha",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("haw",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("he",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("hi",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true, Many: true}, true)
	register("hnj",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("hr",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true}, true)
	register("hsb",
		Rules{Other: true, One: true, Two: true, Few: true},
		Rules{Other: true}, true)
	register("hu",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("hy",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("ia",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("id",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("ig",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("ii",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("io",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("is",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("it",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, Many: true}, true)
	register("iu",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("ja",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("jbo",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("jgo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("jmc",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("jv",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("jw",
		Rules{Other: true},
		Rules{Other: true}, false)
	register("ka",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Many: true}, true)
	register("kab",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("kaj",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("kcg",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("kde",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("kea",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("kk",
		Rules{Other: true, One: true},
		Rules{Other: true, Many: true}, true)
	register("kkj",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("kl",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("km",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("kn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ko",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("ks",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ksb",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ksh",
		Rules{Other: true, Zero: true, One: true},
		Rules{Other: true}, true)
	register("ku",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("kw",
		Rules{Other: true, Zero: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true, One: true, Many: true}, true)
	register("ky",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("lag",
		Rules{Other: true, Zero: true, One: true},
		Rules{Other: true}, true)
	register("lb",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("lg",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("lij",
		Rules{Other: true, One: true},
		Rules{Other: true, Many: true}, true)
	register("lkt",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("lld",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, Many: true}, true)
	register("ln",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("lo",
		Rules{Other: true},
		Rules{Other: true, One: true}, true)
	register("lt",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("lv",
		Rules{Other: true, Zero: true, One: true},
		Rules{Other: true}, true)
	register("mas",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("mg",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("mgo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("mk",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Many: true}, true)
	register("ml",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("mn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("mo",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true, One: true}, false)
	register("mr",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true}, true)
	register("ms",
		Rules{Other: true},
		Rules{Other: true, One: true}, true)
	register("mt",
		Rules{Other: true, One: true, Two: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("my",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("nah",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("naq",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("nb",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nd",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ne",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("nl",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nnh",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("no",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nqo",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("nr",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nso",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ny",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("nyn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("om",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("or",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Two: true, Few: true, Many: true}, true)
	register("os",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("osa",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("pa",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("pap",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("pcm",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("pl",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("prg",
		Rules{Other: true, Zero: true, One: true},
		Rules{Other: true}, true)
	register("ps",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("pt",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true}, true)
	register("pt-PT",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true}, false)
	register("rm",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ro",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true, One: true}, true)
	register("rof",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ru",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("rwk",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("sah",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("saq",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("sat",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("sc",
		Rules{Other: true, One: true},
		Rules{Other: true, Many: true}, true)
	register("scn",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, Many: true}, true)
	register("sd",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("sdh",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("se",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("seh",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ses",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("sg",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("sh",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true}, false)
	register("shi",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true}, true)
	register("si",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("sk",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true}, true)
	register("sl",
		Rules{Other: true, One: true, Two: true, Few: true},
		Rules{Other: true}, true)
	register("sma",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("smi",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("smj",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("smn",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("sms",
		Rules{Other: true, One: true, Two: true},
		Rules{Other: true}, true)
	register("sn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("so",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("sq",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true, Many: true}, true)
	register("sr",
		Rules{Other: true, One: true, Few: true},
		Rules{Other: true}, true)
	register("ss",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ssy",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("st",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("su",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("sv",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, true)
	register("sw",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("syr",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ta",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("te",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("teo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("th",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("ti",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("tig",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("tk",
		Rules{Other: true, One: true},
		Rules{Other: true, Few: true}, true)
	register("tl",
		Rules{Other: true, One: true},
		Rules{Other: true, One: true}, false)
	register("tn",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("to",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("tpi",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("tr",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ts",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("tzm",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ug",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("uk",
		Rules{Other: true, One: true, Few: true, Many: true},
		Rules{Other: true, Few: true}, true)
	register("ur",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("uz",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("ve",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("vec",
		Rules{Other: true, One: true, Many: true},
		Rules{Other: true, Many: true}, true)
	register("vi",
		Rules{Other: true},
		Rules{Other: true, One: true}, true)
	register("vo",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("vun",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("wa",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("wae",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("wo",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("xh",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("xog",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("yi",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
	register("yo",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("yue",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("zh",
		Rules{Other: true},
		Rules{Other: true}, true)
	register("zu",
		Rules{Other: true, One: true},
		Rules{Other: true}, true)
}
